---
- hosts: local
  sudo: yes
  vars:
    home_dir: "/home/berto/"
    install_dir: "{{ home_dir }}install/"
    download_dir: "{{ home_dir }}Downloads/"

  tasks:

  # setup directory structure
  - name: Create var dirs if not available.
    file: >
        path=/home/{{ local_user }}/{{ item }}
        owner={{ local_user }}
        group={{ local_user }}
        mode=0755
        state=directory
    with_items:
      - 'workspace'

  # NOTE: split in ruby-dev, python-dev, common, vagrant roles.

  # Common packages
  - name: Install common packages
    apt: pkg={{ item }}
    with_items:
      - screen
      - nano
      - debian-goodies
      - cmake
      - rake
      - ruby-dev
      - python-dev
      - git-core
      - tmux
      - imagemagick
      - pandoc
      - exuberant-ctags
      - htop
      - ipython
      - python-ipdb
      - markdown
      - cifs-utils
      - curl
      - ack-grep
      - pgadmin3
      - zsh
      - autojump
      - libreoffice
      - cmus
      - npm
      - sshpass
      - xclip
      - smbclient

  # Chrome
  - name: "apt | ensure Google linux signing key present"
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

  - name: "apt | ensure Google chrome repo present"
    apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present

  - name: "apt | ensure Google chrome present"
    apt: name=google-chrome-stable update_cache=yes

  # Sublime
  - name: Get SublimeText deb file
    sudo: no
    get_url: url="https://download.sublimetext.com/sublime-text_build-3126_amd64.deb" dest="{{ install_dir }}sublime.deb"

  - name: Install SublimeText
    apt: deb="{{ install_dir }}sublime.deb"

  # remove unneeded packages
  - name: Remove unneeded packages
    apt: pkg={{ item }} state=absent purge=True
    with_items:
      - gnumeric
      - abiword
      - thunderbird
      - gnome-mines
      - gnome-sudoku
      - orage
      - gnome-user-guide
      - gimp-help-en
      - libdnet
      - dnet-common
      - avahi-daemon
      - vlc
      - cifs-utils

  # Vagrant
  - name: Get vagrant deb file
    become: no
    get_url: url="https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb" dest="{{ download_dir }}vagrant.deb"

  - name: Install Vagrant
    apt: deb="{{ download_dir }}vagrant.deb"

  - name: Install vagrant lxc dependencies.
    apt: pkg={{ item }} 
    with_items:
      - redir
      - bridge-utils
      - lxc
      - lxc-templates
      - cgroup-lite

  - name: List vagrant plugins
    command: vagrant plugin list
    register: vagrant_plugins

  - name: Install Vagrant lxc provider.
    become: no
    shell: vagrant plugin install vagrant-lxc
    when: '"vagrant-lxc" not in vagrant_plugins'
